Ultralytics 8.3.25 ðŸš€ Python-3.11.10 torch-2.5.1+cu124 CUDA:0 (NVIDIA A100-SXM4-80GB, 81156MiB)
YOLO11m-cls summary (fused): 138 layers, 10,344,194 parameters, 0 gradients, 39.3 GFLOPs
[34m[1mtrain:[0m /home/datpham/datpham/ACNE11-Classification/datasets/train... found 3525 images in 12 classes âœ… 
[34m[1mval:[0m /home/datpham/datpham/ACNE11-Classification/datasets/val... found 235 images in 12 classes âœ… 
[34m[1mtest:[0m None...

[34m[1mval: [0mScanning /home/datpham/datpham/ACNE11-Classification/datasets/val... 235 images, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 235/235 [00:00<?, ?it/s]
[34m[1mval: [0mScanning /home/datpham/datpham/ACNE11-Classification/datasets/val... 235 images, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 235/235 [00:00<?, ?it/s]

               classes   top1_acc   top5_acc:   0%|          | 0/15 [00:00<?, ?it/s]
               classes   top1_acc   top5_acc:   7%|â–‹         | 1/15 [00:01<00:18,  1.34s/it]
               classes   top1_acc   top5_acc:  13%|â–ˆâ–Ž        | 2/15 [00:02<00:13,  1.06s/it]
               classes   top1_acc   top5_acc:  20%|â–ˆâ–ˆ        | 3/15 [00:02<00:08,  1.43it/s]
               classes   top1_acc   top5_acc:  27%|â–ˆâ–ˆâ–‹       | 4/15 [00:02<00:05,  1.92it/s]
               classes   top1_acc   top5_acc:  40%|â–ˆâ–ˆâ–ˆâ–ˆ      | 6/15 [00:02<00:02,  3.51it/s]
               classes   top1_acc   top5_acc:  53%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Ž    | 8/15 [00:02<00:01,  5.41it/s]
               classes   top1_acc   top5_acc:  67%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹   | 10/15 [00:03<00:00,  7.03it/s]
               classes   top1_acc   top5_acc:  80%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  | 12/15 [00:03<00:00,  8.77it/s]
               classes   top1_acc   top5_acc:  93%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Ž| 14/15 [00:03<00:00, 10.30it/s]
               classes   top1_acc   top5_acc: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 15/15 [00:03<00:00,  4.35it/s]
Traceback (most recent call last):
  File "/home/datpham/.conda/envs/plant/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/ultralytics/cfg/__init__.py", line 826, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/ultralytics/engine/model.py", line 635, in val
    validator(model=self.model)
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/ultralytics/engine/validator.py", line 200, in __call__
    self.finalize_metrics()
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/ultralytics/models/yolo/classify/val.py", line 64, in finalize_metrics
    self.confusion_matrix.process_cls_preds(self.pred, self.targets)
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/ultralytics/utils/metrics.py", line 319, in process_cls_preds
    self.matrix[p][t] += 1
    ~~~~~~~~~~~~~~^^^
IndexError: index 8 is out of bounds for axis 0 with size 2
Exception in thread Thread-2 (_pin_memory_loop):
Traceback (most recent call last):
  File "/home/datpham/.conda/envs/plant/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/datpham/.conda/envs/plant/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 59, in _pin_memory_loop
    do_one_step()
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 35, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
         ^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/multiprocessing/connection.py", line 519, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/multiprocessing/connection.py", line 647, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
